org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
android.overridePathCheck=true
android.suppressUnsupportedCompileSdk=36
kotlin.incremental=false
kotlin.project.persistent.dir=C:/Users/liu-j/AppData/Local/Temp/codex-kotlin-persistent
kotlin.user.home=C:/Users/liu-j/AppData/Local/Temp/codex-kotlin-home

android.useAndroidX=true
