package llc.slacker.openime.core

import android.content.Context
import android.graphics.Paint

/**
 * The emoji panel's categories: [ImeData.emojiByCategory]'s curated order
 * (its smileys have bundled Fluent images), then every other Unicode emoji
 * of that category from assets/emoji/unicode_emoji.tsv (generated by
 * scripts/generate_emoji_catalog.py). Emoji the phone's font cannot draw are
 * left out, so an older phone shows no empty boxes for newer emoji.
 */
object EmojiCatalog {
    private const val ASSET = "emoji/unicode_emoji.tsv"

    @Volatile
    private var cached: LinkedHashMap<String, List<String>>? = null

    fun byCategory(context: Context): LinkedHashMap<String, List<String>> {
        cached?.let { return it }
        return synchronized(this) {
            cached ?: build(context).also { cached = it }
        }
    }

    private fun build(context: Context): LinkedHashMap<String, List<String>> {
        val extra = LinkedHashMap<String, MutableList<String>>()
        runCatching {
            context.assets.open(ASSET).bufferedReader(Charsets.UTF_8).useLines { lines ->
                lines.forEach { line ->
                    if (line.isBlank() || line.startsWith('#')) return@forEach
                    val tab = line.indexOf('\t')
                    if (tab > 0) extra.getOrPut(line.substring(0, tab)) { ArrayList() } += line.substring(tab + 1)
                }
            }
        }
        val paint = Paint()
        return merge(ImeData.emojiByCategory, extra) { emoji -> paint.hasGlyph(emoji) }
    }

    /** Curated first, then the catalog's additions; [drawable] filters both. */
    internal fun merge(
        curated: Map<String, List<String>>,
        extra: Map<String, List<String>>,
        drawable: (String) -> Boolean,
    ): LinkedHashMap<String, List<String>> {
        val result = LinkedHashMap<String, List<String>>()
        curated.forEach { (category, emoji) ->
            // Compare without the variation selector: ❤ and ❤️ are one emoji.
            val seen = HashSet<String>()
            val list = (emoji + extra[category].orEmpty())
                .filter { seen.add(it.replace("️", "")) }
                .filter(drawable)
            result[category] = list
        }
        return result
    }
}
