package llc.slacker.openime.core

/**
 * One fuzzy-pinyin pair the user can switch on or off on its own.
 *
 * The eleven pairs are the ones mainstream IMEs offer (Sogou, Baidu, iFlytek,
 * Microsoft Pinyin): six initials and five finals. All start off
 * ([defaultOn]); the user turns on the ones their accent needs.
 *
 * Each pair works both ways and is defined twice, kept equal by tests: [rime]
 * is the librime speller algebra (written to openime_fuzzy.yaml), [variants]
 * the same mapping for the Kotlin fallback and the nine-key decoder.
 */
enum class FuzzyRule(
    val key: String,
    val label: String,
    val initial: Boolean,
    val defaultOn: Boolean,
    val rime: List<String>,
) {
    Z_ZH("z_zh", "z = zh", true, false, listOf("derive/^zh/z/", "derive/^z([^h])/zh\$1/")),
    C_CH("c_ch", "c = ch", true, false, listOf("derive/^ch/c/", "derive/^c([^h])/ch\$1/")),
    S_SH("s_sh", "s = sh", true, false, listOf("derive/^sh/s/", "derive/^s([^h])/sh\$1/")),
    N_L("n_l", "n = l", true, false, listOf("derive/^n/l/", "derive/^l/n/")),
    F_H("f_h", "f = h", true, false, listOf("derive/^f/h/", "derive/^h/f/")),
    R_L("r_l", "r = l", true, false, listOf("derive/^r/l/", "derive/^l/r/")),
    AN_ANG("an_ang", "an = ang", false, false, listOf("derive/^([^iuv]*)an\$/\$1ang/", "derive/^([^iuv]*)ang\$/\$1an/")),
    EN_ENG("en_eng", "en = eng", false, false, listOf("derive/en\$/eng/", "derive/eng\$/en/")),
    IN_ING("in_ing", "in = ing", false, false, listOf("derive/in\$/ing/", "derive/ing\$/in/")),
    IAN_IANG("ian_iang", "ian = iang", false, false, listOf("derive/ian\$/iang/", "derive/iang\$/ian/")),
    UAN_UANG("uan_uang", "uan = uang", false, false, listOf("derive/uan\$/uang/", "derive/uang\$/uan/")),
    ;

    /** The other spelling of [syllable] under this pair, or null when it does not apply. */
    fun variant(syllable: String): String? = when (this) {
        Z_ZH -> swapInitial(syllable, "zh", "z")
        C_CH -> swapInitial(syllable, "ch", "c")
        S_SH -> swapInitial(syllable, "sh", "s")
        N_L -> swapInitial(syllable, "n", "l")
        F_H -> swapInitial(syllable, "f", "h")
        R_L -> swapInitial(syllable, "r", "l")
        AN_ANG -> if (syllable.dropLastWhile { it != 'a' }.dropLast(1).none { it in "iuv" }) {
            swapFinal(syllable, "ang", "an")
        } else {
            null
        }
        EN_ENG -> swapFinal(syllable, "eng", "en")
        IN_ING -> swapFinal(syllable, "ing", "in")
        IAN_IANG -> swapFinal(syllable, "iang", "ian")
        UAN_UANG -> swapFinal(syllable, "uang", "uan")
    }

    companion object {
        val DEFAULTS: Set<FuzzyRule> = entries.filter { it.defaultOn }.toSet()

        fun fromKey(key: String): FuzzyRule? = entries.firstOrNull { it.key == key }

        fun fromLabel(label: String): FuzzyRule? = entries.firstOrNull { it.label == label }

        /**
         * openime_fuzzy.yaml for [rules]: the `rules` list the fuzzy schema
         * patches into its speller algebra, in the order of [entries].
         */
        fun rimeYaml(rules: Set<FuzzyRule>): String = buildString {
            append("# Generated by openIME from the 模糊音 switches; do not edit.\n")
            append("rules:\n")
            val lines = entries.filter { it in rules }.flatMap { it.rime }
            if (lines.isEmpty()) {
                append("  __append: []\n")
            } else {
                append("  __append:\n")
                lines.forEach { append("    - ").append(it).append('\n') }
            }
        }

        // "z" must not match the start of "zh" (and "c"/"ch", "s"/"sh").
        private fun swapInitial(syllable: String, a: String, b: String): String? = when {
            syllable.startsWith(a) && !(a.length == 1 && syllable.startsWith(a + "h") && a in "zcs") ->
                b + syllable.substring(a.length)
            syllable.startsWith(b) && !(b.length == 1 && syllable.startsWith(b + "h") && b in "zcs") ->
                a + syllable.substring(b.length)
            else -> null
        }

        // Longer final first: "ang" before "an", "eng" before "en", ...
        private fun swapFinal(syllable: String, long: String, short: String): String? = when {
            syllable.endsWith(long) -> syllable.dropLast(long.length) + short
            syllable.endsWith(short) -> syllable.dropLast(short.length) + long
            else -> null
        }
    }
}
