#!/usr/bin/env python3
"""Generate openIME's full emoji list from Unicode's emoji-test.txt.

    curl -sSfLO https://unicode.org/Public/emoji/latest/emoji-test.txt
    python3 scripts/generate_emoji_catalog.py emoji-test.txt

Writes app/src/main/assets/emoji/unicode_emoji.tsv: one "category<TAB>emoji"
line per fully-qualified emoji, in Unicode's order, without skin-tone or
hair variants (the panel shows each emoji once). The emoji panel keeps its
curated order and appends what this list adds; emoji the phone's font cannot
draw are dropped at runtime. Unicode data terms:
https://www.unicode.org/terms_of_use.html
"""

import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "app" / "src" / "main" / "assets" / "emoji" / "unicode_emoji.tsv"

# Unicode emoji groups -> the panel's categories (ImeData.emojiByCategory keys).
GROUPS = {
    "Smileys & Emotion": "笑脸",
    "People & Body": "人物/手势",
    "Animals & Nature": "动物/自然",
    "Food & Drink": "食物/饮品",
    "Travel & Places": "旅行/地点",
    "Activities": "活动",
    "Objects": "物品",
    "Symbols": "符号",
    "Flags": "旗帜",
}
# Skin tones and hair styles: the panel lists the base emoji only.
VARIANTS = set(range(0x1F3FB, 0x1F400)) | {0x1F9B0, 0x1F9B1, 0x1F9B2, 0x1F9B3}


def main():
    source = Path(sys.argv[1])
    text = source.read_text(encoding="utf-8")
    version = re.search(r"^# Version: (\S+)", text, re.M).group(1)
    group = None
    rows = []
    for line in text.splitlines():
        if line.startswith("# group: "):
            group = GROUPS.get(line[len("# group: "):].strip())
            continue
        if group is None or not line or line.startswith("#"):
            continue
        codes, _, rest = line.partition(";")
        if not rest.strip().startswith("fully-qualified"):
            continue
        points = [int(code, 16) for code in codes.split()]
        if any(point in VARIANTS for point in points):
            continue
        rows.append((group, "".join(chr(point) for point in points)))
    OUT.write_text(
        f"# Unicode emoji {version}, fully-qualified, no skin-tone or hair variants.\n"
        "# Generated by scripts/generate_emoji_catalog.py from emoji-test.txt; do not edit.\n"
        + "".join(f"{category}\t{emoji}\n" for category, emoji in rows),
        encoding="utf-8",
    )
    print(f"{len(rows)} emoji (Unicode {version}) -> {OUT.relative_to(OUT.parents[5])}")


if __name__ == "__main__":
    main()
