#!/usr/bin/env python3
"""Synthesize openIME's built-in key-click sounds.

Every sound is generated here from sine partials and seeded noise, so the
files carry no third-party rights and can be regenerated byte for byte:

    python3 scripts/generate_key_sounds.py

Writes 48 kHz mono 16-bit WAV files to app/src/main/res/raw/key_sound_*.wav.
Each click is under 80 ms and peaks at -2 dBFS; playback volume follows the
system sound level.
"""

import math
import random
import struct
import wave
from pathlib import Path

RATE = 48_000
PEAK = 10 ** (-2 / 20)
OUT = Path(__file__).resolve().parent.parent / "app" / "src" / "main" / "res" / "raw"


def samples(duration_s):
    return int(RATE * duration_s)


def noise(n, seed):
    rnd = random.Random(seed)
    raw = [rnd.uniform(-1.0, 1.0) for _ in range(n + 1)]
    # First difference: tilts the noise toward the treble so it reads as a tick.
    return [raw[i + 1] - raw[i] for i in range(n)]


def decay(t, tau):
    return math.exp(-t / tau)


def finish(signal):
    """Normalise to PEAK and fade the last 2 ms to silence (no end click)."""
    top = max(abs(s) for s in signal) or 1.0
    scaled = [s * PEAK / top for s in signal]
    fade = samples(0.002)
    for i in range(fade):
        scaled[-1 - i] *= i / fade
    return scaled


def crisp():
    n = samples(0.028)
    hiss = noise(n, 11)
    out = []
    for i in range(n):
        t = i / RATE
        out.append(
            0.7 * hiss[i] * decay(t, 0.0012)
            + 0.6 * math.sin(2 * math.pi * 4200 * t) * decay(t, 0.005)
        )
    return finish(out)


def mechanical():
    n = samples(0.055)
    hiss = noise(n, 23)
    second = samples(0.012)
    out = []
    for i in range(n):
        t = i / RATE
        press = (
            0.8 * hiss[i] * decay(t, 0.0018)
            + 0.5 * math.sin(2 * math.pi * 2400 * t) * decay(t, 0.004)
            + 0.3 * math.sin(2 * math.pi * 180 * t) * decay(t, 0.008)
        )
        bottom = 0.0
        if i >= second:
            tb = (i - second) / RATE
            bottom = (
                0.45 * hiss[i - second] * decay(tb, 0.0015)
                + 0.35 * math.sin(2 * math.pi * 1300 * tb) * decay(tb, 0.006)
            )
        out.append(press + bottom)
    return finish(out)


def wood():
    n = samples(0.06)
    hiss = noise(n, 37)
    out = []
    for i in range(n):
        t = i / RATE
        out.append(
            0.8 * math.sin(2 * math.pi * 950 * t) * decay(t, 0.011)
            + 0.35 * math.sin(2 * math.pi * 2300 * t) * decay(t, 0.005)
            + 0.3 * hiss[i] * decay(t, 0.0009)
        )
    return finish(out)


def typewriter():
    n = samples(0.075)
    hiss = noise(n, 41)
    out = []
    for i in range(n):
        t = i / RATE
        ring = sum(math.sin(2 * math.pi * f * t) for f in (3150, 4730, 6210)) / 3
        out.append(
            0.9 * hiss[i] * decay(t, 0.0028)
            + 0.3 * ring * decay(t, 0.016)
            + 0.3 * math.sin(2 * math.pi * 220 * t) * decay(t, 0.01)
        )
    return finish(out)


def bubble():
    duration = 0.045
    n = samples(duration)
    phase = 0.0
    out = []
    for i in range(n):
        t = i / RATE
        freq = 500 + 900 * (t / duration) ** 0.6
        phase += 2 * math.pi * freq / RATE
        envelope = math.sin(math.pi * t / duration) ** 1.5 * decay(t, 0.03)
        out.append(math.sin(phase) * envelope)
    return finish(out)


SOUNDS = {
    "key_sound_crisp": crisp,
    "key_sound_mechanical": mechanical,
    "key_sound_wood": wood,
    "key_sound_typewriter": typewriter,
    "key_sound_bubble": bubble,
}


def write(name, signal):
    path = OUT / f"{name}.wav"
    with wave.open(str(path), "wb") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(RATE)
        wav.writeframes(b"".join(struct.pack("<h", int(round(s * 32767))) for s in signal))
    return path


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, make in SOUNDS.items():
        path = write(name, make())
        print(f"{path.relative_to(OUT.parents[4])}: {path.stat().st_size} bytes")


if __name__ == "__main__":
    main()
